# Prefix

set -g prefix C-Space
set -g prefix2 C-b

bind C-Space send-prefix

# General

set -g mouse on

# =========================
# Status Bar
# =========================

set -g status-position top

set -g status-style "bg=#000000,fg=#7f849c"

set -g status-left-length 20
set -g status-right-length 50

set -g window-status-separator ""

set -g status-left "#[fg=#89b4fa,bold] #S "

set -g window-status-format "#[fg=#6c7086] #I:#W "
set -g window-status-current-format "#[fg=#cdd6f4,bold] #I:#W "

set -g status-right '#{?client_prefix,#[fg=#f9e2af]PREFIX ,}#{?pane_in_mode,#[fg=#f38ba8]COPY ,}#[fg=#6c7086]%H:%M '

set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#89b4fa"

set -g message-style "bg=#000000,fg=#89b4fa"
set -g mode-style "bg=#89b4fa,fg=#000000"

# Splits

bind | split-window -h
bind - split-window -v

# Navigation

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# TPM

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
